import csv

datasets = [
    # 'ACSF1',
    # 'AllGestureWiimoteX', run locally with NaN_to_Num
    # 'AllGestureWiimoteY',
    # 'AllGestureWiimoteZ',
    # 'BME',
    # 'Chinatown',
    'Crop',
    # 'DodgerLoopDay',
    # 'DodgerLoopGame',
    # 'DodgerLoopWeekend',
    'EOGHorizontalSignal',
    'EOGVerticalSignal',
    'EthanolLevel',
    # 'FacesUCR',
    'FordA',
    # 'FordB',
    'FreezerRegularTrain',
    'FreezerSmallTrain',
    'Fungi',
    'GestureMidAirD1',
    'GestureMidAirD2',
    'GestureMidAirD3',
    'GesturePebbleZ1',
    'GesturePebbleZ2',
    'GunPointAgeSpan',
    'GunPointMaleVersusFemale',
    'GunPointOldVersusYoung',
    'HandOutlines',
    # 'Haptics',
    # 'Herring',
    'HouseTwenty',
    # 'InlineSkate',
    'InsectEPGRegularTrain',
    'InsectEPGSmallTrain',
    # 'InsectWingbeatSound',
    # 'ItalyPowerDemand',
    # 'LargeKitchenAppliances',
    # 'Lightning2',
    # 'Lightning7',
    # 'Mallat',
    # 'Meat',
    # 'MedicalImages',
    # 'MelbournePedestrian',
    # 'MiddlePhalanxOutlineCorrect',
    'MixedShapesSmallTrain',
    'NonInvasiveFetalECGThorax1',
    'NonInvasiveFetalECGThorax2',
    # 'OSULeaf',
    # 'OliveOil',
    'PLAID',
    # 'PhalangesOutlinesCorrect',
    # 'Phoneme',
    'PickupGestureWiimoteZ',
    'PigAirwayPressure',
    'PigArtPressure',
    'PigCVP',
    # 'Plane',
    'PowerCons',
    # 'ProximalPhalanxOutlineAgeGroup',
    # 'ProximalPhalanxOutlineCorrect',
    # 'ProximalPhalanxTW',
    # 'RefrigerationDevices',
    # 'Rock',
    'SemgHandGenderCh2',
    'SemgHandMovementCh2',
    'SemgHandSubjectCh2',
    'ShakeGestureWiimoteZ',
    # 'SmoothSubspace',
    'StarlightCurves',
    # 'Strawberry',
    # 'SwedishLeaf',
    'Symbols',
    # 'SyntheticControl',
    # 'ToeSegmentation1',
    # 'ToeSegmentation2',
    # 'Trace',
    'UMD',
    'UWaveGestureLibraryAll',
    # 'Wafer',
    # 'Wine',
    # 'WordSynonyms',
    # 'Worms',
    # 'WormsTwoClass',
    'Yoga'
]
print(f"Number of datasets: {len(datasets)}")

with open('datasets.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Dataset'])
    for dataset in datasets:
        writer.writerow([dataset])